-- Fix missing profile-role table and recursive RLS, and ensure the active model version exists.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    role text not null check (role in ('student', 'admin')),
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Avoid recursive access to public.profiles: read only the JWT claims, never a subquery on the table itself.
drop policy if exists "profiles_users_can_read_own_profile" on public.profiles;
create policy "profiles_users_can_read_own_profile"
on public.profiles
for select
to authenticated
using (
    id = auth.uid()
);

drop policy if exists "profiles_admin_can_read_all" on public.profiles;
create policy "profiles_admin_can_read_all"
on public.profiles
for select
to authenticated
using (
    coalesce(
        auth.jwt() -> 'app_metadata' ->> 'role',
        auth.jwt() ->> 'user_role',
        auth.jwt() ->> 'role'
    ) = 'admin'
);

drop policy if exists "profiles_users_can_insert_own_profile" on public.profiles;
create policy "profiles_users_can_insert_own_profile"
on public.profiles
for insert
to authenticated
with check (
    id = auth.uid()
    and coalesce(
        auth.jwt() -> 'app_metadata' ->> 'role',
        auth.jwt() ->> 'user_role',
        auth.jwt() ->> 'role'
    ) in ('student', 'admin')
);

drop policy if exists "profiles_users_can_update_own_profile" on public.profiles;
create policy "profiles_users_can_update_own_profile"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- Ensure the project table required by repository._get_active_model_version_id exists.
create table if not exists public.model_versions (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    artifact_sha256 char(64) unique not null,
    sklearn_version varchar(30),
    feature_order json,
    is_active boolean default false,
    created_at timestamptz default now()
);

alter table public.model_versions enable row level security;

drop policy if exists "authenticated users can read model versions" on public.model_versions;
create policy "authenticated users can read model versions"
on public.model_versions
for select
to authenticated
using (true);

drop policy if exists "admins can insert model versions" on public.model_versions;
create policy "admins can insert model versions"
on public.model_versions
for insert
to authenticated
with check (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() ->> 'user_role', auth.jwt() ->> 'role') = 'admin'
);

drop policy if exists "admins can update model versions" on public.model_versions;
create policy "admins can update model versions"
on public.model_versions
for update
to authenticated
using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() ->> 'user_role', auth.jwt() ->> 'role') = 'admin'
)
with check (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() ->> 'user_role', auth.jwt() ->> 'role') = 'admin'
);

drop policy if exists "admins can delete model versions" on public.model_versions;
create policy "admins can delete model versions"
on public.model_versions
for delete
to authenticated
using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() ->> 'user_role', auth.jwt() ->> 'role') = 'admin'
);

insert into public.model_versions (
    name,
    artifact_sha256,
    sklearn_version,
    feature_order,
    is_active
)
select
    'Ridge',
    'd3866aae2335834b161a36aa2c7a88b388807e68216bedf6cea57148df94a604',
    '1.9.1',
    '["Attendance", "Hours_Studied", "Previous_Scores", "Tutoring_Sessions", "Access_to_Resources", "Parental_Involvement"]'::json,
    true
where not exists (
    select 1 from public.model_versions where name = 'Ridge' and is_active = true
)
on conflict (artifact_sha256) do update
set is_active = excluded.is_active;
