-- Habit-tracker data model, per the original product vision: raw timestamped
-- events with a start/stop/correction cycle in one generic table, aggregated
-- into the six ML features by the backend -- never collected as a single
-- "type the numbers" form. A small set of slowly-changing student attributes
-- that aren't naturally an "activity" (Previous_Scores, Access_to_Resources,
-- Parental_Involvement) live on profiles instead.

-- 1. Static attributes on profiles.
alter table public.profiles
    add column if not exists previous_scores numeric(5,2) check (previous_scores between 0 and 100),
    add column if not exists access_to_resources text check (access_to_resources in ('Low','Medium','High')),
    add column if not exists parental_involvement text check (parental_involvement in ('Low','Medium','High'));

-- 2. Every signup gets a profiles row automatically. Role is always 'student'
-- here too, for the same reason as 20260922_02_remove_insecure_role_sync_trigger.sql:
-- it must never be derived from data the client supplied at signup.
create or replace function public.create_profile_on_signup()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'student')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_profile_on_signup on auth.users;
create trigger create_profile_on_signup
after insert on auth.users
for each row
execute function public.create_profile_on_signup();

-- 3. profiles.role was previously changeable by anyone through the ordinary
-- authenticated update path: "profiles_users_can_update_own_profile" only
-- checked id = auth.uid(), never that the role column stayed the same. Lock
-- it: an authenticated request (PostgREST sets request.jwt.claims per call)
-- can never change its own role; a direct SQL Editor / service-role action --
-- the only sanctioned way to promote an admin -- has no such claim set and is
-- unaffected.
create or replace function public.prevent_role_self_update()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if new.role is distinct from old.role
     and coalesce(current_setting('request.jwt.claims', true), '') <> ''
  then
    new.role = old.role;
  end if;
  return new;
end;
$$;

drop trigger if exists prevent_role_self_update on public.profiles;
create trigger prevent_role_self_update
before update on public.profiles
for each row
execute function public.prevent_role_self_update();

-- 4. The insert policy had the same gap: it checked the CALLER's own JWT role,
-- never the row being written, so an authenticated student could insert their
-- own profile row with role='admin'. A self-inserted profile is always 'student'
-- (this is now also redundant with the auto-created row from #2, but the
-- policy is kept correct in case a row is ever inserted through this path).
drop policy if exists "profiles_users_can_insert_own_profile" on public.profiles;
create policy "profiles_users_can_insert_own_profile"
on public.profiles
for insert
to authenticated
with check (
    id = auth.uid()
    and role = 'student'
);

-- 5. Generic activity log: one row per raw event. activity_type says what it
-- is, status says where it is in its lifecycle. Valid (type, status)
-- combinations are enforced by the API, not the database -- genericity by
-- metadata over one table per behavioural variable, as originally decided.
create table if not exists public.activity_logs (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    activity_type text not null check (activity_type in ('study_session', 'tutoring_session', 'attendance')),
    status text not null check (status in ('in_progress', 'completed', 'cancelled', 'present', 'absent', 'corrected')),
    started_at timestamptz not null,
    ended_at timestamptz,
    corrected_from bigint references public.activity_logs(id),
    note text,
    created_at timestamptz not null default now(),
    constraint activity_logs_ended_after_started check (ended_at is null or ended_at >= started_at)
);

create index if not exists activity_logs_user_started_idx
on public.activity_logs (user_id, started_at desc);

create index if not exists activity_logs_user_type_idx
on public.activity_logs (user_id, activity_type);

alter table public.activity_logs enable row level security;

drop policy if exists "students can read their own activity logs" on public.activity_logs;
create policy "students can read their own activity logs"
on public.activity_logs
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "admins can read all activity logs" on public.activity_logs;
create policy "admins can read all activity logs"
on public.activity_logs
for select
to authenticated
using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
);

drop policy if exists "students can insert their own activity logs" on public.activity_logs;
create policy "students can insert their own activity logs"
on public.activity_logs
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "students can update their own activity logs" on public.activity_logs;
create policy "students can update their own activity logs"
on public.activity_logs
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
