-- Student Performance Predictor: model registry.

create table if not exists public.model_versions (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    artifact_sha256 char(64) unique not null,
    sklearn_version varchar(30),
    feature_order json,
    is_active boolean default false,
    created_at timestamptz default now()
);

insert into public.model_versions (
    name,
    artifact_sha256,
    sklearn_version,
    feature_order,
    is_active
)
values (
    'Ridge',
    'd3866aae2335834b161a36aa2c7a88b388807e68216bedf6cea57148df94a604',
    '1.9.1',
    '["Attendance", "Hours_Studied", "Previous_Scores", "Tutoring_Sessions", "Access_to_Resources", "Parental_Involvement"]'::json,
    true
)
on conflict (artifact_sha256) do update
set is_active = excluded.is_active;

alter table public.model_versions enable row level security;

drop policy if exists "authenticated users can read model versions"
on public.model_versions;
create policy "authenticated users can read model versions"
on public.model_versions
for select
to authenticated
using (true);

drop policy if exists "admins can insert model versions"
on public.model_versions;
create policy "admins can insert model versions"
on public.model_versions
for insert
to authenticated
with check (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() ->> 'user_role') = 'admin'
);

drop policy if exists "admins can update model versions"
on public.model_versions;
create policy "admins can update model versions"
on public.model_versions
for update
to authenticated
using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() ->> 'user_role') = 'admin'
)
with check (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() ->> 'user_role') = 'admin'
);

drop policy if exists "admins can delete model versions"
on public.model_versions;
create policy "admins can delete model versions"
on public.model_versions
for delete
to authenticated
using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() ->> 'user_role') = 'admin'
);